### ISSUE TITLE
Running REPL Fails

### ISSUE THREAD

**Issue by sdiemert** [salesforce/runway-compiler#12]
Hi, 

Running the REPL as described in the README seems to fail... 

Command history: 
```
  504  git clone https://github.com/salesforce/runway-compiler.git
  ...
  506  cd runway-compiler/
  ...
  509  npm install
  ...
  513  node bin/main.js
```

Error message from node: 

```
/.../runway/runway-compiler/lib/pubsub.js:30
        results.push(handler(...arguments));
                             ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/../runway/runway-compiler/lib/workspace.js:15:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

System info: 

* Mac OSX 10.11.5
* Node: 4.4.3
* NPM: 2.15.1

I just removed the `...` that seemed to be causing the issue in `lib/pubsub.js` and the REPL runs fine. Not sure if this is actually the fix or I have horribly broken something. 

Cheers

**Comment by ongardie-sfdc** [comment]
Hi @sdiemert, I think your Node is a bit old. You might get by with passing --harmony to it, as described here: https://groups.google.com/d/msg/runway-dev/CUQIds_Qqj4/g7tLryqcAQAJ

Please keep this issue open as a reminder to add a note to the README.
